[package]
name = "flymoon"
build = "build.rs"
version.workspace = true
edition.workspace = true

[dependencies]
bot.workspace = true
log.workspace = true
toml.workspace = true
duct.workspace = true
image.workspace = true
sqldb.workspace = true
serde.workspace = true
cutil.workspace = true
regex.workspace = true
slint.workspace = true
cfg-if.workspace = true
anyhow.workspace = true
qrcode.workspace = true
clipboard.workspace = true
once_cell.workspace = true
webbrowser.workspace = true
derivative.workspace = true
serde_with.workspace = true
serde_json.workspace = true
env_logger.workspace = true
display-info.workspace = true
platform-dirs.workspace = true
dummy_markdown.workspace = true
pmacro.workspace = true
paste.workspace = true
uuid = { workspace = true, features = ["v4"] }
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
duct.workspace = true
embed-resource.workspace = true
slint-build.workspace = true

[features]
default = [
  "database",
  "center-window",
  "cutil/http",
  "cutil/time",
  "cutil/crypto",
]
database = []
qrcode = []
center-window = []

[[bin]]
path = "src/desktop.rs"
name = "flymoon"
