import { Theme, Icons } from "../../theme.slint";
import { Util } from "../../util.slint";
import { Logic } from "../../logic.slint";
import { Store } from "../../store.slint";
import { SettingIconsBar }  from "../setting/desktop.slint";

import { Search, Label  } from "../../base/widgets.slint";

component HistoryList inherits Rectangle {
    background: red;
}

export component History inherits VerticalLayout {
    init => {
        search.focus();
    }

    VerticalLayout {
        padding: Theme.padding;
        spacing: Theme.spacing;

        search := Search {
            values: Store.search-entries;
            enabled-popup: true;

            search(text) => {
            }

            edited(text) => {
            }
        }

        HistoryList { }
    }
}
