import { Theme, Icons } from "../../theme.slint";
import { Util } from "../../util.slint";
import { Logic } from "../../logic.slint";
import { Store, TabIndex } from "../../store.slint";
import { SettingIconsBar }  from "../setting/desktop.slint";

import { History } from "history.slint";
import { Chat } from "chat/panel.slint";

export component Home inherits Rectangle {
    if Store.current-tab-index == TabIndex.Home: Chat {}
    if Store.current-tab-index == TabIndex.History: History {}
}
