import { Theme, Store, TabIndex, SettingDetailIndex, Logic, Icons } from "../def.slint";
import { SettingDialog, AboutDialog, HelpDialog, DonateDialog, SettingIconsBar } from "../setting/desktop.slint";
import { Blanket, StatusBar, Divider, AboutSetting, ToolTip, ToolTipSetting, PopupAction, PopupActionSetting, ComponentPosition, IconBtn } from "../../base/widgets.slint";
import { Home } from "home.slint";

component HomeIconsBar inherits Rectangle {
    width: hbox.preferred-width;
    height: hbox.preferred-height;
    border-radius: Theme.border-radius;

    in-out property <bool> show-icon-hover-background: false;
    in-out property <length> icon-size: Theme.icon-size;
    in-out property <bool> is-show-tip: false;
    in-out property <ComponentPosition> tip-position;
    in-out property h-padding <=> hbox.padding;
    in-out property h-spacing <=> hbox.spacing;

    hbox := HorizontalLayout {
        padding: Theme.padding * 2;
        spacing: Theme.spacing * 4;

        IconBtn {
            icon: Icons.chat;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("chat");

            clicked => {
                Logic.switch-tab(TabIndex.Home);
            }
        }

        IconBtn {
            icon: Icons.notify;
            icon-size: root.icon-size;
            show-icon-hover-background: root.show-icon-hover-background;
            is-show-tip: root.is-show-tip;
            tip-position: root.tip-position;
            tip: Logic.tr("history");

            clicked => {
                Logic.switch-tab(TabIndex.History);
            }
        }
    }
}

export component DesktopPanel inherits Rectangle {
    private property <bool> is-show-setting-dialog: Store.current-tab-index == TabIndex.Setting;
    private property <bool> is-show-about-dialog: Store.current-tab-index == TabIndex.About;
    private property <bool> is-show-help-dialog: Store.current-tab-index == TabIndex.Help;
    private property <bool> is-show-donate-dialog: Store.current-tab-index == TabIndex.Donate;

    private property <length> home-height: self.height;

    VerticalLayout {
        if Store.setting-preference.no-frame: sb := StatusBar {
            background: Theme.secondary-background;
            is-show-icon: true;
            icon: Icons.brand;
            title: AboutSetting.app-name;
            is-show-tip: true;
            disable-maximal: true;

            init => {
                root.home-height = root.height - self.preferred-height;
            }

            HorizontalLayout {
                padding-right: Theme.padding * 2;

                HomeIconsBar {
                    icon-size: Theme.default-font-size;
                    h-spacing: Theme.spacing * 3;
                    show-icon-hover-background: false;
                    is-show-tip: sb.is-show-tip;
                    tip-position: sb.tip-position;
                }

                VerticalLayout {
                    alignment: LayoutAlignment.center;
                    Divider {
                        height: Theme.default-font-size;
                        width: 2px;
                    }
                }

                SettingIconsBar {
                    icon-size: Theme.default-font-size;
                    h-spacing: Theme.spacing * 3;
                    show-icon-hover-background: false;
                    is-show-tip: sb.is-show-tip;
                    tip-position: sb.tip-position;
                }

                VerticalLayout {
                    alignment: LayoutAlignment.center;
                    Divider {
                        height: Theme.default-font-size;
                        width: 2px;
                    }
                }
            }
        }

        Home {
            // uncomment it to set real height
            // height: root.home-height;
        }
    }

    if is-show-setting-dialog || is-show-about-dialog || is-show-help-dialog || is-show-donate-dialog: Blanket {
        clicked => {
            Logic.switch-tab(TabIndex.Back);
        }
    }

    if is-show-setting-dialog: SettingDialog {
        width: Math.min(1300px, root.width * 0.95);
    }

    if is-show-about-dialog: AboutDialog {
        width: Math.min(1300px, root.width * 0.95);
    }

    if is-show-help-dialog: HelpDialog {
        width: Math.min(1300px, root.width * 0.95);
    }

    if is-show-donate-dialog: DonateDialog {
        width: Math.min(1300px, root.width * 0.95);
    }

    if PopupActionSetting.is-show: PopupAction {
        window-width: root.width;
        window-height: root.height;
    }

    if ToolTipSetting.is-show: ToolTip {
        window-width: root.width;
        window-height: root.height;
    }
}
