import { Theme, Logic, Store } from "../../def.slint";
import { Session } from "session.slint";
import { Input } from "input.slint";
import { Divider } from "../../../base/widgets.slint";

export component Chat inherits VerticalLayout {
    in-out property <length> win-height;
    in-out property question <=> input.question;

    padding: Theme.padding * 2;
    spacing: Theme.spacing * 2;

    session := Session { }
    input := Input { }
}
