import { ListView } from "std-widgets.slint";
import { Theme, Store, Logic, Icons } from "../../def.slint";
import { ChatEntry} from "../../../store.slint";
import { ElevatedBtn, Label, CenterLayout, PopupActionSetting } from "../../../base/widgets.slint";

component ChatDetail inherits HorizontalLayout {
    in-out property text <=> txt.text;

    in-out property <bool> is-user;
    in-out property <bool> read-only: true;

    callback key-pressed <=> txt.key-pressed;

    alignment: is-user ? LayoutAlignment.end : LayoutAlignment.start;

    Rectangle {
        background: is-user ? Theme.thirdly-brand-color : Theme.hover-background;
        border-top-left-radius: Theme.border-radius * 3;
        border-top-right-radius: is-user ? Theme.border-radius * 6 : Theme.border-radius * 3;
        border-bottom-left-radius: Theme.border-radius * 3;
        border-bottom-right-radius: is-user ? 0 : Theme.border-radius * 3;
        width: Math.min(root.width * (is-user ? 0.8 : 1), vbox.preferred-width);
        height: vbox.preferred-height;

        vbox := VerticalLayout {
            padding: Theme.padding * 2;
            padding-left: Theme.padding * 4;
            padding-right: Theme.padding * 4;
            alignment: LayoutAlignment.center;

            HorizontalLayout {
                alignment: LayoutAlignment.end;

                txt := TextInput {
                    wrap: word-wrap;
                    color: is-user ? Theme.light-text-color : Theme.primary-text-color;
                    font-size: Theme.title4-font-size;
                    single-line: false;
                    read-only: root.read-only;
                    text-cursor-width: Theme.default-text-cursor-width;
                }
            }
        }
    }
}

component User inherits Rectangle {
    in-out property <int> index;
    in-out property <ChatEntry> entry;

    height: user.preferred-height;

    user := ChatDetail {
        is-user: true;
        text: entry.user;
        read-only: !entry.is-user-edit;

        key-pressed(event) => {
            if (event.text == Key.Escape) {
                entry.is-user-edit = false;
                accept
            }
            reject
        }
    }

    if !uta.enabled: ElevatedBtn {
        x: parent.width - user.preferred-width - self.width - Theme.padding * 4;
        width: Theme.icon-size + Theme.padding * 2;
        icon: Icons.checked;
        colorize: Theme.success-color;

        clicked => {
            entry.is-user-edit = false;
            Logic.retry-question(index, user.text);
        }
    }

    uta := TouchArea {
        enabled: !entry.is-user-edit;
        mouse-cursor: self.enabled ? MouseCursor.pointer : MouseCursor.default;
        double-clicked => {
            entry.is-user-edit = true;
        }

        pointer-event(event) => {
            if (event.button == PointerEventButton.right) {
                PopupActionSetting.show(parent.absolute-position.x + self.mouse-x, parent.absolute-position.y + self.mouse-y, [
                    {
                        icon: Icons.send,
                        text: "Retry",
                        action: "retry-question",
                        user-data: index,
                    },
                    {
                        icon: Icons.copy-fill,
                        text: "Copy",
                        action: "copy-question",
                        user-data: user.text,
                    },
                    {
                        icon: Icons.edit,
                        text: "Edit",
                        action: "edit-question",
                        user-data: index,
                    },
                    {
                        icon: Icons.delete-fill,
                        text: "Remove",
                        action: "remove-question",
                        user-data: index,
                    },
                ]);
            }
        }
    }
}

export component Session inherits Rectangle {
    public function scroll-to-top() {
        lv.viewport-y = 0;
    }

    public function scroll-to-bottom() {
        lv.viewport-y = Math.min(0, -lv.viewport-height + lv.visible-height);
    }

    public function scroll-up() {
        lv.viewport-y = Math.min(0, lv.viewport-y + lv.visible-height / 4);
    }

    public function scroll-down() {
        lv.viewport-y = Math.min(0, Math.max(lv.viewport-y - lv.visible-height / 4, -lv.viewport-height + lv.visible-height));
    }

    public function jump-to-viewport-y(vy: length) {
        lv.viewport-height = Math.clamp(vy, 0, -vy + lv.visible-height);
    }

    public function is-near-bottom() -> bool {
        lv.viewport-y <= -lv.viewport-height + (lv.visible-height * 1.2);
    }

    public function scroll-auto() {
        if (is-near-bottom()) {
            scroll-to-bottom();
        }
    }

    Timer {
        interval: 100ms;
        running: Store.is-chatting;
        triggered() => {
            scroll-auto();
        }
    }

    VerticalLayout {
        if Store.current-chat-session.histories.length == 0 && !Store.current-model-name.is-empty: Label {
            horizontal-alignment: TextHorizontalAlignment.center;
            text: Store.current-model-name;
            color: Theme.disabled-color;
        }

        lv := ListView {
            width: root.width;
            height: root.height;
            vertical-scrollbar-policy: always-off;

            for entry[index] in Store.current-chat-session.histories: VerticalLayout {
                padding: Theme.padding * 2;
                padding-top: 0;
                padding-bottom: Theme.padding * 4;
                spacing: Theme.spacing * 3;

                if index == 0 && !Store.current-model-name.is-empty: Label {
                    horizontal-alignment: TextHorizontalAlignment.center;
                    text: Store.current-model-name;
                    color: Theme.disabled-color;
                }

                user := User {
                    index: index;
                    entry: entry;
                }

                if !entry.bot.is_empty: ChatDetail {
                    text: entry.bot;
                }
            }
        }
    }
}
