import { Theme, Logic, Store, Icons, Util, TabIndex } from "../../def.slint";
import { ChatPhase, PromptType } from "../../../store.slint";
import { Divider, ElevatedBtn, IconBtn, TextBtn, ToastStatus} from "../../../base/widgets.slint";

export component Input inherits Rectangle {
    in-out property question <=> te.text;

    private property <bool> is-ctrl-pressed;

    callback scroll-up;
    callback scroll-down;
    callback scroll-to-top;
    callback scroll-to-bottom;

    height: 130px;
    forward-focus: te;

    function update-height(height: length) {
        root.height = Math.clamp(height, 130px, Theme.default-height / 3 * 2);
    }

    function ensure-show-cursor() {
        if (flick.viewport-height <= flick.height) {
            flick.viewport-y = 0;
        } else {
            if (-flick.viewport-y + te.font-size * 2 < flick.viewport-height - flick.height) {
                return;
            }
            flick.viewport-y = -flick.viewport-height + flick.height;
        }
    }

    function send-question() {
        if (root.question.is-empty) {
            return;
        }
        Logic.send-question(question);
        root.question = "";
        ensure-show-cursor();
        Store.is-auto-scroll = true;
    }

    function toggle-current-model-name() {
        Store.enabled-reasoner-model = !Store.enabled-reasoner-model;

        if (Store.enabled-reasoner-model) {
            Store.current-model-name = Logic.get-setting-model().chat.reasoner-model-name;
        } else {
            Store.current-model-name = Logic.get-setting-model().chat.model-name;
        }
    }

    function toggle-search-webpages() {
        if (!Store.search-webpages-available) {
            Util.show-toast(Logic.tr("Please go to the 'Settings' page and configure the 'Google Search' related settings"), ToastStatus.Info);
            return;
        }
        Store.enabled-search-webpages = !Store.enabled-search-webpages;
    }

    init => {
        te.focus();
    }

    Rectangle {
        border-radius: Theme.border-radius * 4;
        border-width: te.has-focus ? 2px : 1px;
        border-color: te.has-focus ? Theme.focus-color : Theme.disabled-color;
        background: Theme.base-background;

        VerticalLayout {
            Rectangle {
                flick := Flickable {
                    y: Theme.padding * 2;

                    changed viewport-height => {
                        root.update-height(self.viewport-height + h-btns.preferred-height);
                    }

                    VerticalLayout {
                        padding: Theme.padding * 2;

                        te := TextInput {
                            single-line: false;
                            wrap: word-wrap;
                            color: Theme.regular-text-color;
                            font-size: Theme.title4-font-size;

                            edited => {
                                if (!self.text.is-empty) {
                                    if (Util.start-with(self.text, "/")) {
                                        Logic.prompt-popup(te.text);
                                    } else if (Util.start-with(self.text, "@")) {
                                        Logic.mcp-popup(te.text);
                                    }
                                }
                                Logic.prompt-popup-clear(self.text);

                                ensure-show-cursor();
                            }

                            key-pressed(event) => {
                                if (event.modifiers.control) {
                                    if (event.text == Key.Return) {
                                        send-question();
                                        return accept;
                                    } else if (event.text == "r") {
                                        Logic.retry-question(Store.current-chat-session.histories.length - 1, "");
                                        scroll-to-bottom();
                                        return accept;
                                    } else if (event.text == "n") {
                                        Logic.new-chat-session();
                                        Store.is-auto-scroll = true;
                                        return accept;
                                    } else if (event.text == "s") {
                                        Logic.stop-question();
                                        return accept;
                                    } else if (event.text == "h") {
                                        Logic.switch-tab(TabIndex.History);
                                        return accept;
                                    } else if (event.text == ",") {
                                        Logic.switch-tab(TabIndex.Setting);
                                        return accept;
                                    } else if (event.text == "q") {
                                        Util.close-window();
                                        return accept;
                                    } else if (event.text == "t") {
                                        root.scroll-to-top();
                                        return accept;
                                    } else if (event.text == "b") {
                                        root.scroll-to-bottom();
                                        return accept;
                                    } else if (event.text == "j") {
                                        root.scroll-down();
                                        return accept;
                                    } else if (event.text == "k") {
                                        root.scroll-up();
                                        return accept;
                                    } else if (event.text == "d") {
                                        toggle-current-model-name();
                                        return accept;
                                    } else if (event.text == "w") {
                                        toggle-search-webpages();
                                        return accept;
                                    } else if (event.text == "y") {
                                        Logic.copy-last-bot-text();
                                        return accept;
                                    } else if (event.text == "m") {
                                        Store.is-toggle-bot-markdown = !Store.is-toggle-bot-markdown;
                                        return accept;
                                    } else if (event.text == "p") {
                                        Store.is-show-current-prompt-dialog = !Store.is-show-current-prompt-dialog;
                                        return accept;
                                    } else if (event.text == "/") {
                                        Logic.clear-current-chat-session-prompt();
                                        return accept;
                                    } else if (event.text == "-") {
                                        Logic.decrease-font-size();
                                        return accept;
                                    } else if (event.text == "=") {
                                        Logic.increase-font-size();
                                        return accept;
                                    }
                                }
                                return reject;
                            }
                        }
                    }
                }

                if false: Text {
                    visible: te.text.is-empty;
                    x: Theme.padding * 2;
                    y: Theme.padding * 4;
                    text: "Ctrl+Enter";
                    font-size: Theme.title4-font-size;
                    color: Theme.placeholder-text-color;
                }
            }

            h-btns := HorizontalLayout {
                height: Theme.icon-size * 2;
                alignment: LayoutAlignment.space-between;

                HorizontalLayout {
                    padding: Theme.padding;
                    padding-left: Theme.padding * 2;
                    spacing: Theme.spacing * 2;
                    alignment: LayoutAlignment.start;

                    if Store.reasoner-model-available: TextBtn {
                        border-color: Store.enabled-reasoner-model ? Theme.thirdly-brand-color : Theme.placeholder-text-color;
                        border-width: self.has-hover || Store.enabled-reasoner-model ? 2px : 1px;
                        border-radius: Theme.border-radius * 4;
                        bg-color: Theme.hover-background;
                        icon: Icons.reasoner;
                        colorize: self.border-color;
                        text: Logic.tr("Reasoner");
                        gain-focus-when-clicked: false;

                        clicked => {
                            toggle-current-model-name();
                        }
                    }

                    TextBtn {
                        border-color: Store.enabled-search-webpages ? Theme.thirdly-brand-color : Theme.placeholder-text-color;
                        border-width: self.has-hover || Store.enabled-search-webpages ? 2px : 1px;
                        border-radius: Theme.border-radius * 4;
                        bg-color: Theme.hover-background;
                        icon: Icons.network;
                        colorize: self.border-color;
                        text: Logic.tr("Network");
                        gain-focus-when-clicked: false;

                        clicked => {
                            toggle-search-webpages();
                        }
                    }
                }

                HorizontalLayout {
                    alignment: LayoutAlignment.end;
                    spacing: Theme.spacing * 4;

                    IconBtn {
                        icon: Store.current-chat-session.prompt-type == PromptType.Normal ? Icons.prompt : Icons.mcp;
                        tip: Store.current-chat-session.prompt-type == PromptType.Normal ? Logic.tr("prompt") : Logic.tr("mcp prompt");

                        is-show-tip: true;
                        gain-focus-when-clicked: false;
                        colorize: Store.current-chat-session.prompt.is-empty ? Theme.icon-color : Theme.warning-color;

                        clicked => {
                            Store.is-show-current-prompt-dialog = true;
                        }
                    }

                    IconBtn {
                        icon: Icons.new;
                        tip: Logic.tr("new");
                        is-show-tip: true;
                        gain-focus-when-clicked: false;

                        clicked => {
                            Logic.new-chat-session();
                            Store.is-auto-scroll = true;
                        }
                    }

                    IconBtn {
                        icon: Icons.retry;
                        tip: Logic.tr("retry");
                        is-show-tip: true;
                        gain-focus-when-clicked: false;

                        clicked => {
                            Logic.retry-question(Store.current-chat-session.histories.length - 1, "");
                            scroll-to-bottom();
                        }
                    }

                    HorizontalLayout {
                        padding-left: Theme.padding * 2;
                        padding-right: Theme.padding * 2;

                        if Store.chat-phase == ChatPhase.None: ElevatedBtn {
                            enable: te.text != "";
                            icon: Icons.send2;
                            colorize: te.text != "" ? Theme.thirdly-brand-color : Theme.disabled-color;
                            icon-rotation-angle: -90deg;
                            gain-focus-when-clicked: false;

                            clicked => {
                                root.send-question();
                            }
                        }

                        if Store.chat-phase != ChatPhase.None: ElevatedBtn {
                            icon: Icons.stop;
                            colorize: Theme.thirdly-brand-color;
                            gain-focus-when-clicked: false;

                            clicked => {
                                Store.chat-phase = ChatPhase.None;
                                Logic.stop-question();
                            }
                        }
                    }
                }
            }
        }
    }
}
