import { Theme, Store } from "../../def.slint";
import { Label } from "../../../base/widgets.slint";

export component InputPromptList inherits Rectangle {
    background: Theme.base-background;
    border-color: Theme.base-border-color;
    border-radius: Theme.border-radius * 2;
    border-width: Theme.default-border-width;

    height: Math.min(200px, vbox.preferred-height);
    width: vbox.preferred-width;

    Flickable {
        vbox := VerticalLayout {
            padding: Theme.padding * 2;
            padding-left: Theme.padding * 4;
            padding-right: Theme.padding * 4;

            private property <length> max-shortcut-label-width;

            for entry[index] in Store.input-prompt-list-entries: HorizontalLayout {
                spacing: Theme.spacing * 5;
                alignment: LayoutAlignment.start;

                shortcut-label := Label {
                    width: max-shortcut-label-width;

                    init => {
                        if (self.preferred-width > max-shortcut-label-width) {
                            max-shortcut-label-width = self.preferred-width;
                        }
                    }

                    font-size: Theme.title4-font-size;
                    text: entry.shortcut;
                }

                name-label := Label {

                    font-size: Theme.title4-font-size;
                    text: entry.name;
                }
            }
        }
    }
}
