import { Theme, Logic, Store } from "../../def.slint";
import { Divider, CenterLayout } from "../../../base/widgets.slint";

import { Input } from "input.slint";
import { Session } from "session.slint";
import { InputPromptList } from "input-prompt-list.slint";

export component Chat inherits VerticalLayout {
    in-out property <length> win-height;
    in-out property question <=> input.question;

    padding: Theme.padding * 2;
    spacing: Theme.spacing * 2;

    Rectangle {
        session := Session { }

        if Store.input-prompt-list-entries.length > 0: InputPromptList {
            x: 0;
            y: input.y - self.height - Theme.padding * 3;
        }
    }

    input := Input {
        scroll-up => {
            session.scroll-up();
        }

        scroll-down => {
            session.scroll-down();
        }

        scroll-to-top => {
            session.scroll-to-top();
        }

        scroll-to-bottom => {
            session.scroll-to-bottom();
        }
    }
}
