import { Theme, Logic, Store } from "../../def.slint";
import { Divider, CenterLayout } from "../../../base/widgets.slint";

import { Input } from "input.slint";
import { Session } from "session.slint";

export component Chat inherits VerticalLayout {
    in-out property <length> win-height;
    in-out property question <=> input.question;

    padding: Theme.padding * 2;
    spacing: Theme.spacing * 2;

    Rectangle {
        session := Session {
            focus-input => {
                input.focus();
            }
        }
    }

    input := Input {
        scroll-up => {
            session.scroll-up();
        }

        scroll-down => {
            session.scroll-down();
        }

        scroll-to-top => {
            session.scroll-to-top();
        }

        scroll-to-bottom => {
            session.scroll-to-bottom();
        }
    }
}
