[package]
name = "bot"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true
cutil = { workspace = true, features = ["http"] }
serde = { workspace = true, features = ["serde_derive"] }
tokio = { workspace = true, features = ["sync", "rt-multi-thread", "macros"] }

[dev-dependencies]
env_logger.workspace = true

[features]
default = []
