#[cfg(any(
    target_os = "windows",
    target_os = "linux",
    target_os = "macos",
    target_os = "android"
))]
use crate::config;

use std::collections::HashMap;

pub fn tr(text: &str) -> String {
    cfg_if::cfg_if! {
        if #[cfg(any(
            target_os = "windows",
            target_os = "linux",
            target_os = "macos",
            target_os = "android"
            ))] {
            if config::preference().language == "en" {
                return text.to_string();
            }
        }
    }

    let items: HashMap<&str, &str> = HashMap::from([
        ("10 ~ 50", "10 ~ 50"),
        ("about", "关于"),
        ("About", "关于"),
        ("Account address", "账户地址"),
        ("Add", "添加"),
        ("Add entry failed", "添加条目失败"),
        ("Add entry successfully", "添加条目成功"),
        ("Address", "地址"),
        ("Address book", "地址簿"),
        ("Address name", "地址名称"),
        ("Advance setting", "高级设置"),
        ("api base url", "API基础URL"),
        ("API base URL", "API基础URL"),
        ("api key", "API密钥"),
        ("API key", "API密钥"),
        ("Apply", "应用"),
        ("At least 8 chars", "至少8个字符"),
        ("Back", "返回"),
        ("Base fee", "基础费用"),
        ("Blockchain network", "区块链网络"),
        ("Cancel", "取消"),
        ("chat", "聊天"),
        ("Chat", "聊天"),
        ("Google Search", "谷歌搜索"),
        ("Chat failed", "聊天失败"),
        ("Choose language", "选择语言"),
        ("Choose Theme", "选择主题"),
        ("close", "关闭"),
        ("Close", "关闭"),
        ("Close window", "关闭窗口"),
        ("Confirm", "确认"),
        ("Cancel select all", "取消全选"),
        ("copy", "复制"),
        ("Copy failed", "复制失败"),
        ("Copy success", "复制成功"),
        ("Create token account fee", "创建代币账户费用"),
        ("cx", "CX"),
        ("CX", "CX"),
        ("Dark", "暗色"),
        ("Delete", "删除"),
        ("Delete address", "删除地址"),
        ("Delete address or not?", "是否删除地址？"),
        ("Delete or not?", "是否删除？"),
        ("Detail", "详情"),
        ("donate", "捐赠"),
        ("Donate", "捐赠"),
        ("Edit", "编辑"),
        ("Evaluating gas fee...", "估算Gas费用中..."),
        ("Evaluating transaction fee failed", "估算交易费用失败"),
        ("Fast", "快速"),
        ("Finished", "完成"),
        ("Font family", "字体"),
        ("Font size", "字体大小"),
        ("github", "GitHub"),
        ("Github", "GitHub"),
        ("height", "高度"),
        ("help", "帮助"),
        ("Help", "帮助"),
        ("history", "历史"),
        (
            "[History Tab]: Enter editing model",
            "[历史标签页]: 进入编辑模式",
        ),
        ("[History Tab]: Toggle select all", "[历史标签页]: 切换全选"),
        ("Home", "首页"),
        ("Icons", "图标"),
        ("Input can not be empty", "输入不能为空"),
        ("Jump to", "跳转到"),
        ("keyword", "关键词"),
        ("Light", "亮色"),
        ("Link number", "链接数量"),
        ("Load entry failed", "加载条目失败"),
        ("Loading...", "加载中..."),
        (
            "Input '/' to show prompts' tip panel at homepage",
            "提问框输入'/' 在首页显示提示面板",
        ),
        ("Log in", "登录"),
        ("maximal", "最大"),
        ("Memo", "备注"),
        ("MetaMask crypto pay", "MetaMask加密支付"),
        ("minimal", "最小"),
        ("mnemonics", "助记词"),
        ("model", "模型"),
        ("Model", "模型"),
        ("Chat model", "对话模型"),
        ("Reasoner model (Optional)", "思考模型（可选）"),
        ("Reasoner", "深度思考"),
        ("Toggle reasoner model", "切换深度思考模式"),
        ("name", "名称"),
        ("Name", "名称"),
        ("Network", "网络搜索"),
        ("new", "新建"),
        ("New chat", "新聊天"),
        ("No Data", "无数据"),
        ("No Message", "无消息"),
        ("normal", "普通"),
        ("Normal", "普通"),
        ("Only support OpenAI compatible API", "仅支持OpenAI兼容API"),
        ("Open link failed", "打开链接失败"),
        ("Password", "密码"),
        ("Paste failed", "粘贴失败"),
        ("Please enter new password", "请输入新密码"),
        ("Please enter old password", "请输入旧密码"),
        ("Please enter password", "请输入密码"),
        ("Please enter password again", "请再次输入密码"),
        ("Please enter username", "请输入用户名"),
        ("Please select language", "请选择语言"),
        ("Preference", "偏好设置"),
        ("Prev", "上一个"),
        ("Prioritization fee", "优先费用"),
        ("Prompt", "提示"),
        ("Proxy", "代理"),
        ("Proxy address", "代理地址"),
        ("Proxy port", "代理端口"),
        ("Quit application or not?", "是否退出应用？"),
        ("Reason", "原因"),
        ("Recipient address", "接收地址"),
        ("References", "参考"),
        ("Refreshing...", "刷新中..."),
        ("Remove entry failed", "移除条目失败"),
        ("Remove entry successfully", "移除条目成功"),
        ("Reset password", "重置密码"),
        ("retry", "重试"),
        ("Retry Last question", "重试上一个问题"),
        ("Scroll dowm", "向下滚动"),
        ("Scroll to bottom", "滚动到底部"),
        ("Scroll to top", "滚动到顶部"),
        ("Scroll up", "向上滚动"),
        ("Search", "搜索"),
        ("Searching...", "搜索中..."),
        ("Search webpages failed", "搜索网页失败"),
        ("Send address", "发送地址"),
        ("Send amount", "发送数量"),
        ("Send question", "发送问题"),
        ("Send token", "发送代币"),
        ("setting", "设置"),
        ("Setting", "设置"),
        ("shortcut", "快捷键"),
        ("Shortcut", "快捷键"),
        ("Shortcuts", "快捷键"),
        ("Sign in", "登录"),
        ("Skip", "跳过"),
        ("Slow", "慢速"),
        ("Stop chatting", "停止聊天"),
        ("Switch to Home or History Tab", "切换到首页或历史标签页"),
        ("Switch to Setting Tab", "切换到设置"),
        ("Select all", "全选"),
        ("Thinking...", "思考中..."),
        ("Toggle Markdown format of Bot", "切换Bot的Markdown格式"),
        ("Toggle network searching", "切换网络搜索"),
        ("Transaction detail", "交易详情"),
        ("Transaction failed", "交易失败"),
        ("Transaction history", "交易历史"),
        ("Transaction signature", "交易签名"),
        ("Transaction success", "交易成功"),
        ("Update entry failed", "更新条目失败"),
        ("Update entry successfully", "更新条目成功"),
        ("Username", "用户名"),
        ("Waiting transaction confirmed...", "等待交易确认中..."),
        ("Warning", "警告"),
        ("Webs", "网页"),
        ("Wechat pay", "微信支付"),
        ("width", "宽度"),
        ("Window size", "窗口大小"),
        ("Temperature", "温度"),
        ("Welcome to the Flymoon!", "欢迎来到Flymoon!"),
        ("You can ask me any questions", "你可以问我任何问题哦"),
        ("Info", "提醒"),
        ("Reboot to take setting effect", "重启使配置生效"),
        ("Frameless window", "无边框窗口"),
        ("Please go to the 'Settings' page and configure the 'Google Search' related settings", "请到「设置」页面并设置「谷歌搜索」相关配置"),
    ]);

    if let Some(txt) = items.get(text) {
        return txt.to_string();
    }

    text.to_string()
}
