export enum DeviceType {
    Desktop,
    Mobile,
    Web,
}

export enum TabIndex {
    Home,
    Setting,
    History,
    About,
    Donate,
    Help,
    Back,
}

export enum SettingDetailIndex {
    Preference,
    Proxy,
    Model,
    Prompt,
}

export struct SettingPreference {
    win-width: string,
    win-height: string,
    font-size: string,
    font-family: string,
    language: string,
    always-on-top: bool,
    no-frame: bool,
    is-dark: bool,
}

export struct SettingProxy {
    proxy-type: string,
    http-url: string,
    http-port: string,
    socks5-url: string,
    socks5-port: string,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////

export struct SettingModel {
    model-name: string,
    api-base-url: string,
    api-key: string,
}

export struct PromptEntry {
    uuid: string,
    name: string,
    shortcut: string,
    detail: string,
}

export struct ChatEntry {
    user: string,
    bot: string,
}

export struct ChatSession {
    uuid: string,
    time: string,
    prompt: string,
    histories: [ChatEntry],
}

export struct ChatHistory {
    uuid: string,
    time: string,
    summary: string,
    checked: bool,
}

//////////////////////////////// Logic Struct End  ////////////////////////////////

export global Store {
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page: false;
    in-out property <DeviceType> device-type: DeviceType.Desktop;

    in-out property <TabIndex> previous-tab-index: TabIndex.Home;
    in-out property <TabIndex> current-tab-index: TabIndex.Home;

    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Preference;

    in-out property <bool> is-cn: setting-preference.language == "cn";
    in-out property <SettingPreference> setting-preference: {
        win-width: 500,
        win-height: 800,
        font-size: "16",
        font-family: "Source Han Sans CN",
        language: "en",
        always-on-top: false,
        no-frame: true,
        is-dark: false,
    };

    in-out property <[string]> helps: is-cn ? [
        "配置文件保存目录: ~/.config/flybot",
        "数据库保存目录: ~/.local/share/flybot",
    ] : [
        "Config directory: ~/.config/flybot",
        "Data directory: ~/.local/share/flybot",
    ];

    //////////////////////////////// Logic Start ////////////////////////////////

    in-out property <bool> enabled-network;

    in-out property <[PromptEntry]> input-prompt-list-entries: [
        // {
        //     shortcut: "cn",
        //     name: "text-1",
        // },
        // {
        //     shortcut: "en",
        //     name: "text-20000000",
        // },
    ];

    in-out property <[PromptEntry]> prompt-entries: [
        // {
        //     uuid: "uuid-1",
        //     name: "text-1",
        //     shortcut: "cn",
        //     detail: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
        // },
        // {
        //     uuid: "uuid-2",
        //     name: "text-2",
        //     shortcut: "en",
        //     detail: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
        //     is-open: false,
        // },
    ];

    in-out property <[ChatHistory]> chat-histories-cache:[];
    in-out property <[ChatHistory]> chat-histories: [
        // {
        //     uuid: "chat-uuid-1",
        //     checked: false,
        //     time: "10-09:23:10",
        //     summary: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
        // },
        // {
        //     uuid: "chat-uuid-2",
        //     checked: true,
        //     time: "10-09:23:20",
        //     summary: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
        // },
    ];

    in-out property <ChatSession> current-chat-session: {
        uuid: "chat-uuid-1",
        prompt: "You are a chat bot",
        histories: [
            {
                user: "hi",
                bot: "how are you?",
            },
            {
                user: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
                bot: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
            },
        ]
    };

    //////////////////////////////// Logic End  ////////////////////////////////
}
