export enum DeviceType {
    Desktop,
    Mobile,
    Web,
}

export enum TabIndex {
    Home,
    Setting,
    History,
    About,
    Donate,
    Help,
    None,
}

export enum SettingDetailIndex {
    Preference,
    Proxy,
    Model,
    Prompt,
    None,
}

export struct SettingPreference {
    win-width: string,
    win-height: string,
    font-size: string,
    font-family: string,
    language: string,
    always-on-top: bool,
    no-frame: bool,
    is-dark: bool,
}

export struct SettingProxy {
    proxy-type: string,
    http-url: string,
    http-port: string,
    socks5-url: string,
    socks5-port: string,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////

export struct SettingModel {
    model-name: string,
    api-base-url: string,
    api-key: string,
}

export struct Prompt {
    uuid: string,
    name: string,
    shortcut: string,
    detail: string,
}

export struct ChatEntry {
    user: string,
    bot: string,
}

export struct ChatHistory {
    prompt: string,
    histories: [ChatEntry],
}

//////////////////////////////// Logic Struct End  ////////////////////////////////

export global Store {
    in-out property <DeviceType> device-type: DeviceType.Desktop;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page: false;

    in-out property <TabIndex> current-tab-index: TabIndex.Home;

    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Preference;

    in-out property <bool> is-cn: setting-preference.language == "cn";
    in-out property <SettingPreference> setting-preference: {
        win-width: 500,
        win-height: 800,
        font-size: "16",
        font-family: "Source Han Sans CN",
        language: "en",
        always-on-top: false,
        no-frame: true,
        is-dark: false,
    };

    in-out property <[string]> helps: is-cn ? [
        "配置文件保存目录: ~/.config/flybot",
        "数据库保存目录: ~/.local/share/flybot",
    ] : [
        "Config directory: ~/.config/flybot",
        "Data directory: ~/.local/share/flybot",
    ];

    //////////////////////////////// Logic Start ////////////////////////////////
    in-out property <[string]> search-entries;
    in-out property <[Prompt]> prompt-entries: [
        {
            uuid: "uuid-1",
            name: "text-1",
            shortcut: "cn",
            detail: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
            is-open: true,
        },
        {
            uuid: "uuid-2",
            name: "text-2",
            shortcut: "en",
            detail: "In NixOS, you can install libalsa (ALSA library) in several ways, depending on how you want to use it. Here are the common methods",
            is-open: false,
        },
    ];
    in-out property <ChatHistory> chat-histories;
    //////////////////////////////// Logic End  ////////////////////////////////
}
