import { Theme, Logic, Store } from "../../def.slint";
import { Label, Paragraph, ParagraphEntry } from "../../../base/widgets.slint";

component SettingHelp inherits VerticalLayout {
    spacing: Theme.spacing * 4;

    private property <[ParagraphEntry]> entries-cn:
    [
        {
            title: "简介",
            title-link: "https://github.com/heng30/flymoon",
            contents: [
                "这是一个基于Rust和Slint GUI构建的大语言模型聊天客户端，兼容OpenAI的API。",
                "1. 支持聊天和深度思考两种聊天模式",
                "2. 自动保存历史聊天记录"
            ],
        },
        {
            title: "如何配置大语言模型？",
            title-link: "https://api-docs.deepseek.com/zh-cn/",
            picture: @image-url("../../../images-help/chat-model-light-cn.png"),
            contents: [
                "1. 「API基础URL」是和OpenAI兼容的API基地址",
                "2. 「思考模型」是可选的",
            ],
        },
        {
            title: "注意事项",
            contents: [
                "1. 在Linux Wayland环境中，「设置 -> 无边框」会使用程序自定义的顶部状态栏。因为在Wayland环境中，程序本身无法设置在屏幕中的位置。所以无法通过拖动顶部状态栏移动程序。需要关闭「无边框」选项，使用系统状态栏。",
                "2. 支持LaTex数学公式方法：到Github->release页面下载latex-image程序，并将其放到系统路径中。"
            ],
        },
    ];

    private property <[ParagraphEntry]> entries-en:
    [
        {
            title: "Introduction",
            title-link: "https://github.com/heng30/flymoon",
            contents: [
                "This is a large language model chat client built with Rust and Slint GUI, compatible with OpenAI's API.",
                "1. Supports both chat and deep thinking modes",
                "2. Automatically saves chat history"
            ],
        },
        {
            title: "How to Configure the LLM?",
            title-link: "https://api-docs.deepseek.com/en/",
            picture: @image-url("../../../images-help/chat-model-light-en.png"),
            contents: [
                "1. 「API base URL」 is the OpenAI-compatible API base address",
                "2. 「Reasoner model」 is optional",
            ],
        },
        {
            title: "Note",
            contents: [
                "1. In a Linux Wayland environment, enabling 「Settings -> Frameless window」 will use the application's custom top status bar. This is because in the Wayland environment, the application itself cannot set its position on the screen. As a result, you cannot move the application by dragging the top status bar. To resolve this, you need to disable the 「Frameless window」 option and use the system status bar instead",
                "2. Supporting LaTeX mathematical formulas method: Go to the GitHub releases page, download the latex-image program, and place it in your system path."
            ],
        },
    ];

    private property <[ParagraphEntry]> entries: Store.is-cn ? entries-cn : entries-en;

    for entry in root.entries: Paragraph {
        entry: entry;
        is-picture-before-contents: true;
        content-font-size: Theme.title4-font-size;
        picture-size: 400px;
    }
}

component ShortcutsHelp inherits VerticalLayout {
    private property <[{shortcut: string, detail: string}]> shortcuts: [
        {
            shortcut: "Ctrl + N",
            detail: Logic.tr("New chat"),
        },
        {
            shortcut: "Ctrl + M",
            detail: Logic.tr("Toggle Markdown format of Bot"),
        },
        {
            shortcut: "Ctrl + S",
            detail: Logic.tr("Stop chatting"),
        },
        {
            shortcut: "Ctrl + R",
            detail: Logic.tr("Retry Last question"),
        },
        {
            shortcut: "Ctrl + K",
            detail: Logic.tr("Scroll up"),
        },
        {
            shortcut: "Ctrl + J",
            detail: Logic.tr("Scroll dowm"),
        },
        {
            shortcut: "Ctrl + T",
            detail: Logic.tr("Scroll to top"),
        },
        {
            shortcut: "Ctrl + B",
            detail: Logic.tr("Scroll to bottom"),
        },
        {
            shortcut: "Ctrl + D",
            detail: Logic.tr("Toggle reasoner model"),
        },
        {
            shortcut: "Ctrl + Y",
            detail: Logic.tr("Copy latest bot responsing contents"),
        },
        {
            shortcut: "Ctrl + Q",
            detail: Logic.tr("Close window"),
        },
        {
            shortcut: "Ctrl + H",
            detail: Logic.tr("Switch to Home or History Tab"),
        },
        {
            shortcut: "Ctrl + ,",
            detail: Logic.tr("Switch to Setting Tab"),
        },
        {
            shortcut: "Ctrl + E",
            detail: Logic.tr("[History Tab]: Enter editing model"),
        },
        {
            shortcut: "Ctrl + T",
            detail: Logic.tr("[History Tab]: Toggle select all"),
        },
        {
            shortcut: "Ctrl + J",
            detail: Logic.tr("[History Tab]: Select next row"),
        },
        {
            shortcut: "Ctrl + K",
            detail: Logic.tr("[History Tab]: Select previous row"),
        },
        {
            shortcut: "Ctrl + +",
            detail: Logic.tr("Increase font size"),
        },
        {
            shortcut: "Ctrl + -",
            detail: Logic.tr("Decrease font size"),
        },
        {
            shortcut: "Ctrl + I",
            detail: Logic.tr("Focus question input box"),
        },
        {
            shortcut: "Enter",
            detail: Logic.tr("Send question"),
        },
    ];

    HorizontalLayout {
        padding-bottom: Theme.padding * 4;
        Label {
            text: Logic.tr("Shortcuts");
            font-size: Theme.title1-font-size;
            font-weight: Theme.bold-font-weight;
        }
    }

    VerticalLayout {
        alignment: LayoutAlignment.start;

        for entry[index] in shortcuts: Rectangle {
            background: Math.mod(index, 2) == 0 ? Theme.hover-background : Colors.transparent;

            HorizontalLayout {
                padding: Theme.padding * 2;

                Label {
                    width: 30%;
                    text: entry.shortcut;
                    overflow: elide;
                }

                Label {
                    text: entry.detail;
                    font-size: Theme.title4-font-size;
                    overflow: elide;
                }
            }
        }
    }
}

export component HelpDetail inherits VerticalLayout {
    spacing: Theme.spacing * 4;
    padding: Theme.padding * 2;

    SettingHelp { }

    ShortcutsHelp { }
}
